### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by ctrlaltde** [kalikao/InfiniteLootBox#1]
Hello there, 

I'm a student and working on a uni project on loot boxes. I really woud like to use your code, however I'm a bit at a loss when trying to use it, when compiling on Unity I get a lot of errors and perhaps I'm doing something wrong. 

Would you be so kind to help me set this program up so it can at least run? 

Cheers,
Uni student

**Comment by kalikao** [comment]
Hi,

This was originally developed 15 months ago, so my suggestion would be to try an older Unity version. The project was working in its entirety at the time, however it's possible that Unity updates have since changed that. Good luck and let me know how that goes!

Best,
Dominic

**Comment by ctrlaltde** [comment]
Hi Dominic,

Has been a while! I've finally managed to run it successfully, perhaps this may be useful in the notes. The Unity version to use is 2018.3.4

Cheers,
Julien

**Comment by kalikao** [comment]
Hi Julien,

Thanks for the update! I've updated the notes.

Best,
Dominic
